// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: appdetail.proto

// protoc -I. --go_out=plugins=grpc:. /appdetail.proto

package appdetail

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAppDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PackageName string `protobuf:"bytes,1,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
}

func (x *GetAppDetailRequest) Reset() {
	*x = GetAppDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appdetail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppDetailRequest) ProtoMessage() {}

func (x *GetAppDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appdetail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppDetailRequest.ProtoReflect.Descriptor instead.
func (*GetAppDetailRequest) Descriptor() ([]byte, []int) {
	return file_appdetail_proto_rawDescGZIP(), []int{0}
}

func (x *GetAppDetailRequest) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

type GetAppDetailReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Detail     *App  `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	StatusCode int32 `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
}

func (x *GetAppDetailReply) Reset() {
	*x = GetAppDetailReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appdetail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppDetailReply) ProtoMessage() {}

func (x *GetAppDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_appdetail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppDetailReply.ProtoReflect.Descriptor instead.
func (*GetAppDetailReply) Descriptor() ([]byte, []int) {
	return file_appdetail_proto_rawDescGZIP(), []int{1}
}

func (x *GetAppDetailReply) GetDetail() *App {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *GetAppDetailReply) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type App struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description  string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Homepage     string   `protobuf:"bytes,3,opt,name=homepage,proto3" json:"homepage,omitempty"`
	Email        string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	AuthorName   string   `protobuf:"bytes,5,opt,name=authorName,proto3" json:"authorName,omitempty"`
	CategoryName string   `protobuf:"bytes,6,opt,name=categoryName,proto3" json:"categoryName,omitempty"`
	Package      *Package `protobuf:"bytes,7,opt,name=package,proto3" json:"package,omitempty"`
}

func (x *App) Reset() {
	*x = App{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appdetail_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_appdetail_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_appdetail_proto_rawDescGZIP(), []int{2}
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *App) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

func (x *App) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *App) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *App) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *App) GetPackage() *Package {
	if x != nil {
		return x.Package
	}
	return nil
}

type Package struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PackageId         uint32   `protobuf:"varint,1,opt,name=packageId,proto3" json:"packageId,omitempty"`
	PackageHash       string   `protobuf:"bytes,2,opt,name=packageHash,proto3" json:"packageHash,omitempty"`
	VersionCode       uint32   `protobuf:"varint,3,opt,name=versionCode,proto3" json:"versionCode,omitempty"`
	VersionName       string   `protobuf:"bytes,4,opt,name=versionName,proto3" json:"versionName,omitempty"`
	MinimumSDKVersion string   `protobuf:"bytes,5,opt,name=minimumSDKVersion,proto3" json:"minimumSDKVersion,omitempty"`
	Permissions       []string `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty"`
}

func (x *Package) Reset() {
	*x = Package{}
	if protoimpl.UnsafeEnabled {
		mi := &file_appdetail_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_appdetail_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_appdetail_proto_rawDescGZIP(), []int{3}
}

func (x *Package) GetPackageId() uint32 {
	if x != nil {
		return x.PackageId
	}
	return 0
}

func (x *Package) GetPackageHash() string {
	if x != nil {
		return x.PackageHash
	}
	return ""
}

func (x *Package) GetVersionCode() uint32 {
	if x != nil {
		return x.VersionCode
	}
	return 0
}

func (x *Package) GetVersionName() string {
	if x != nil {
		return x.VersionName
	}
	return ""
}

func (x *Package) GetMinimumSDKVersion() string {
	if x != nil {
		return x.MinimumSDKVersion
	}
	return ""
}

func (x *Package) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_appdetail_proto protoreflect.FileDescriptor

var file_appdetail_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x70, 0x70, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x61, 0x70, 0x70, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x38, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x26, 0x0a, 0x06, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70,
	0x70, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x41, 0x70, 0x70, 0x52, 0x06, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x22, 0xdf, 0x01, 0x0a, 0x03, 0x41, 0x70, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x70, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x07, 0x70, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x22, 0xdd, 0x01, 0x0a, 0x07, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x20, 0x0a, 0x0b, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d,
	0x53, 0x44, 0x4b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x11, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x53, 0x44, 0x4b, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0x59, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x4c, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x70, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x70, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x70, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x70, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x70, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_appdetail_proto_rawDescOnce sync.Once
	file_appdetail_proto_rawDescData = file_appdetail_proto_rawDesc
)

func file_appdetail_proto_rawDescGZIP() []byte {
	file_appdetail_proto_rawDescOnce.Do(func() {
		file_appdetail_proto_rawDescData = protoimpl.X.CompressGZIP(file_appdetail_proto_rawDescData)
	})
	return file_appdetail_proto_rawDescData
}

var file_appdetail_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_appdetail_proto_goTypes = []interface{}{
	(*GetAppDetailRequest)(nil), // 0: appdetail.GetAppDetailRequest
	(*GetAppDetailReply)(nil),   // 1: appdetail.GetAppDetailReply
	(*App)(nil),                 // 2: appdetail.App
	(*Package)(nil),             // 3: appdetail.Package
}
var file_appdetail_proto_depIdxs = []int32{
	2, // 0: appdetail.GetAppDetailReply.detail:type_name -> appdetail.App
	3, // 1: appdetail.App.package:type_name -> appdetail.Package
	0, // 2: appdetail.AppDetail.GetAppDetail:input_type -> appdetail.GetAppDetailRequest
	1, // 3: appdetail.AppDetail.GetAppDetail:output_type -> appdetail.GetAppDetailReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_appdetail_proto_init() }
func file_appdetail_proto_init() {
	if File_appdetail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_appdetail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appdetail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppDetailReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appdetail_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_appdetail_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Package); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_appdetail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_appdetail_proto_goTypes,
		DependencyIndexes: file_appdetail_proto_depIdxs,
		MessageInfos:      file_appdetail_proto_msgTypes,
	}.Build()
	File_appdetail_proto = out.File
	file_appdetail_proto_rawDesc = nil
	file_appdetail_proto_goTypes = nil
	file_appdetail_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AppDetailClient is the client API for AppDetail service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppDetailClient interface {
	GetAppDetail(ctx context.Context, in *GetAppDetailRequest, opts ...grpc.CallOption) (*GetAppDetailReply, error)
}

type appDetailClient struct {
	cc grpc.ClientConnInterface
}

func NewAppDetailClient(cc grpc.ClientConnInterface) AppDetailClient {
	return &appDetailClient{cc}
}

func (c *appDetailClient) GetAppDetail(ctx context.Context, in *GetAppDetailRequest, opts ...grpc.CallOption) (*GetAppDetailReply, error) {
	out := new(GetAppDetailReply)
	err := c.cc.Invoke(ctx, "/appdetail.AppDetail/GetAppDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppDetailServer is the server API for AppDetail service.
type AppDetailServer interface {
	GetAppDetail(context.Context, *GetAppDetailRequest) (*GetAppDetailReply, error)
}

// UnimplementedAppDetailServer can be embedded to have forward compatible implementations.
type UnimplementedAppDetailServer struct {
}

func (*UnimplementedAppDetailServer) GetAppDetail(context.Context, *GetAppDetailRequest) (*GetAppDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppDetail not implemented")
}

func RegisterAppDetailServer(s *grpc.Server, srv AppDetailServer) {
	s.RegisterService(&_AppDetail_serviceDesc, srv)
}

func _AppDetail_GetAppDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppDetailServer).GetAppDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appdetail.AppDetail/GetAppDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppDetailServer).GetAppDetail(ctx, req.(*GetAppDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppDetail_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appdetail.AppDetail",
	HandlerType: (*AppDetailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAppDetail",
			Handler:    _AppDetail_GetAppDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "appdetail.proto",
}
